[package]
name = "seeddot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitfield = "0.14"
clap = { version = "4.3", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rand = "0.8"
plotters = "0.3.6"
